from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(900, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 120, 461, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 3500, 70))
        self.label.setObjectName("label")
        self.controlBox = QtWidgets.QGroupBox(self.centralwidget)
        self.controlBox.setGeometry(QtCore.QRect(560, 400, 291, 211))
        self.controlBox.setObjectName("controlBox")
        self.nextButton = QtWidgets.QPushButton(self.controlBox)
        self.nextButton.setGeometry(QtCore.QRect(30, 50, 90, 28))
        self.nextButton.setObjectName("nextButton")
        self.previousButton = QtWidgets.QPushButton(self.controlBox)
        self.previousButton.setGeometry(QtCore.QRect(160, 50, 90, 28))
        self.previousButton.setObjectName("previousButton")
        self.uploadButton = QtWidgets.QPushButton(self.controlBox)
        self.uploadButton.setGeometry(QtCore.QRect(30, 140, 90, 28))
        self.uploadButton.setObjectName("uplodeButton")
        self.updateButton = QtWidgets.QPushButton(self.controlBox)
        self.updateButton.setGeometry(QtCore.QRect(160, 140, 90, 28))
        self.updateButton.setObjectName("updateButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(720, 650, 90, 28))
        self.exitButton.setObjectName("exitButton")
        self.chatBox = QtWidgets.QGroupBox(self.centralwidget)
        self.chatBox.setGeometry(QtCore.QRect(560, 120, 281, 231))
        self.chatBox.setObjectName("chatBox")
        self.inputTextEdit = QtWidgets.QTextEdit(self.chatBox)
        self.inputTextEdit.setGeometry(QtCore.QRect(20, 170, 150, 30))
        self.inputTextEdit.setObjectName("inputTextEdit")
        self.textEdit = QtWidgets.QTextEdit(self.chatBox)
        self.textEdit.setGeometry(QtCore.QRect(20, 40, 241, 101))
        self.textEdit.setObjectName("textEdit")
        self.SendButton = QtWidgets.QPushButton(self.chatBox)
        self.SendButton.setGeometry(QtCore.QRect(190, 170, 71, 30))
        self.SendButton.setObjectName("SendButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuData_veiw = QtWidgets.QMenu(self.menubar)
        self.menuData_veiw.setObjectName("menuData_veiw")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChoose_Data_Sourse = QtWidgets.QAction(MainWindow)
        self.actionChoose_Data_Sourse.setObjectName("actionChoose_Data_Sourse")
        self.actionMerge_database = QtWidgets.QAction(MainWindow)
        self.actionMerge_database.setObjectName("actionMerge_database")
        #self.actionSign_out = QtWidgets.QAction(MainWindow)
        #self.actionSign_out.setObjectName("actionSign_out")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionChoose_Data_Sourse)
        self.menuFile.addAction(self.actionMerge_database)
        #self.menuFile.addAction(self.actionSign_out)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData_veiw.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "White shark tracking"))
        self.label.setText(_translate("MainWindow", "White shark feature data"))
        self.controlBox.setTitle(_translate("MainWindow", "Control box"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.uploadButton.setText(_translate("MainWindow", "Upload"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.chatBox.setTitle(_translate("MainWindow", "Chat box"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuData_veiw.setTitle(_translate("MainWindow", "Data view"))
        self.actionChoose_Data_Sourse.setText(_translate("MainWindow", "Choose Data Source"))
        self.actionMerge_database.setText(_translate("MainWindow", "Merge database"))
        #self.actionSign_out.setText(_translate("MainWindow", "Sign out"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
