# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uplode.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 250)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(225, 15, 50, 31))
        self.label_3.setObjectName("label_3")
        self.mergeButton = QtWidgets.QPushButton(Form)
        self.mergeButton.setGeometry(QtCore.QRect(100, 190, 100, 31))
        self.mergeButton.setObjectName("mergeButton")
        self.quitButton = QtWidgets.QPushButton(Form)
        self.quitButton.setGeometry(QtCore.QRect(300, 190, 100, 31))
        self.quitButton.setObjectName("quitButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 60, 441, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TlineEdit = QtWidgets.QLineEdit(self.widget)
        self.TlineEdit.setObjectName("TlineEdit")
        self.gridLayout.addWidget(self.TlineEdit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.SButton = QtWidgets.QPushButton(self.widget)
        self.SButton.setObjectName("SButton")
        self.gridLayout.addWidget(self.SButton, 1, 4, 1, 1)
        self.SlineEdit = QtWidgets.QLineEdit(self.widget)
        self.SlineEdit.setObjectName("SlineEdit")
        self.gridLayout.addWidget(self.SlineEdit, 1, 2, 1, 1)
        self.TButton = QtWidgets.QPushButton(self.widget)
        self.TButton.setObjectName("TButton")
        self.gridLayout.addWidget(self.TButton, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(15, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "White shark tracking"))
        self.label_3.setText(_translate("Form", "Upload"))
        self.mergeButton.setText(_translate("Form", "Merge"))
        self.quitButton.setText(_translate("Form", "Quit"))
        self.label_2.setText(_translate("Form", "Source File"))
        self.SButton.setText(_translate("Form", "Select"))
        self.TButton.setText(_translate("Form", "Select"))
        self.label.setText(_translate("Form", "Target File"))
